### ISSUE TITLE
nested routes on api.wm.o break rest adapter for individual projects

### ISSUE THREAD

**Issue by ashleygwilliams** [mozilla/webmaker-moderator#1]
`Ember.RESTAdapter` wants shallow routes. click through to an individual project looks for "project/:id".

we need to either:
A. customize the adapter to deal with nested routes
B. implement shallow routes for projects on `api.wm.o`

B is the best option in my opinion as the nested routes are an anti-pattern. because the `project_id` is application unique, adding the route would be just that, and would require no more code change.

@jbuck @simonwex @cadecairos?

**Comment by ashleygwilliams** [comment]
relevant issue on `api.wm.o`: https://github.com/mozilla/api.webmaker.org/issues/133

**Comment by ashleygwilliams** [comment]
there is also an option C, where instead of fullying implementing shallow routes for `projects` we can simply fwd the nested routes to the shallow ones. since the extra info in the nested route is completely unecessary there is no loss of info.

this is probably the easiest and least disruptive while still moving in the right direction decision.

**Comment by jbuck** [comment]
C does sound like the right path here, especially if it's just adding another route to existing handlers. As @cadecairos pointed out in the linked issue, we definitely need to be careful about cache invalidation.

**Comment by ashleygwilliams** [comment]
FWIW, @jbuck, i dont think cache invalidation will be an issue whether we have real routes or fwds as we dont need cache on our shallow route. we are simply adding in either case, nothing destructive.

**Comment by jbuck** [comment]
But maybe the existing route handlers do something like cache based on request.url? I'm not entirely certain. We just gotta be careful is all!

**Comment by cadecairos** [comment]
If we're just talking about a shallow project route, we shouldn't need to get fancy with cache invalidation, since  there's no elements/pages to invalidate.

**Comment by ashleygwilliams** [comment]
careful is good :ok_hand: :+1:

**Comment by ashleygwilliams** [comment]
WIP PR here: https://github.com/mozilla/api.webmaker.org/pull/155

**Comment by ashleygwilliams** [comment]
this is solved.
